import {StyleSheet} from 'react-native';
import {DeviceWidth} from '@config/environment';
import {SecondaryColor} from '@config/environment';
export default styles = StyleSheet.create({
  groupedWrapper: {
    backgroundColor: '#fff',
    padding: 5,
    borderRadius: 3,
    marginTop: 5,
    marginBottom: 5,
    elevation: 1.5,
    shadowColor: '#bfbfbf',
    shadowOffset: {
      height: 0,
      width: 0,
    },
    freebieImage: {width: 40, height: 20},
    shadowOpacity: 0.5,
    shadowRadius: 2,
    borderWidth: 1,
    borderColor: '#C7C7C7',
  },
  groupedProductNameWrapper: {
    width: DeviceWidth - 80,
    marginBottom: 5,
    paddingTop: 4,
  },
  groupedProductName: {
    fontSize: 13,
    color: '#212121',
  },
  productGroupedPriceInfoWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  productNewpriceWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  currency: {
    fontSize: 12,
  },
  productNewprice: {
    fontSize: 25,
    color: '#212121',
    marginRight: 5,
  },
  productOldprice: {
    textDecorationLine: 'line-through',
    textDecorationStyle: 'solid',
    fontSize: 12,
    color: '#21212180',
    marginRight: 5,
    color: '#bbbbbb',
  },
  productDiscount: {
    color: 'green',
    fontSize: 13,
  },
  reviewsWrapper: {
    flexDirection: 'row',
    marginLeft: 7,
  },
  ratingBoxWrapper: {
    flexDirection: 'row',
    backgroundColor: '#1abf46',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 3,
    paddingLeft: 3,
    paddingRight: 3,
  },
  ratingBox: {
    color: '#fff',
    marginRight: 2,
    fontSize: 12,
  },
  ratingBoxIcon: {
    color: '#fff',
    fontSize: 12,
  },
  reviewsQty: {
    marginLeft: 5,
    fontSize: 12,
    color: '#21212180',
  },
  availablityWrapper: {
    backgroundColor: 'red',
    position: 'absolute',
    // top: 5,
    right: 5,
    paddingVertical: 1,
    paddingHorizontal: 5,
    borderRadius: 20,
  },
  soldOutText: {
    fontSize: 10,
    color: '#fff',
  },
  tierPrice: {
    fontSize: 11,
    color: '#00a324',
  },
  tierPriceWrapper: {
    marginBottom: 5,
  },
  deliveryFee: {
    fontSize: 12,
    color: 'blue',
  },
  groupedQuantityWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modalWrapper: {
    width: '100%',
    position: 'absolute',
    bottom: 0,
    backgroundColor: '#fff',
    paddingTop: 15,
    paddingBottom: 15,
    paddingLeft: 20,
    paddingRight: 20,
    borderTopColor: '#ddd',
    borderWidth: 0.5,
    shadowColor: '#bfbfbf',
    shadowOpacity: 0.5,
    shadowOffset: {
      height: 0,
      width: 0,
    },
    elevation: 1,
    zIndex: 2,
  },
  modalCloseButton: {
    paddingTop: 4,
    paddingBottom: 4,
    paddingLeft: 10,
    paddingRight: 8,
    borderRadius: 12,
    backgroundColor: SecondaryColor,
    color: '#fff',
    textAlign: 'center',
    width: 130,
    marginTop: 10,
  },
  tierTable: {
    width: '65%',
    borderColor: 'black',
    height: 30,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#25303c',
  },
  tierTablee: {
    width: '35%',
    borderColor: 'black',
    height: 30,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#25303c',
  },
  tierTableText: {
    color: 'white',
  },
  tierPrices: {
    marginBottom: 5,
    width: '100%',
    height: 30,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'grey',
    // backgroundColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  tierPricesText: {
    // color: 'white',
    fontWeight: '600',
  },
  tierTableList: {
    width: '65%',
    borderColor: 'black',
    height: 30,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: '#fad091',
  },
  tierTableList2: {
    width: '35%',
    borderColor: 'black',
    height: 30,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: '#fad091',
  },
  tierTableListText: {
    color: 'black',
  },
  itemCount: {
    fontWeight: '600',
    color: 'black',
  },
  mrp: {
    textDecorationLine: 'line-through',
  },
  itemCountPrice: {
    fontWeight: '600',
    color: 'black',
    fontSize: 20,
  },
  shareIconOnProduct: {
    // width: 22,
    // height: 22,
    // tintColor: 'black',
    resizeMode: 'contain',
    width: 80,
    height: 30,
  },
  sharePressIcon: {
    position: 'absolute',
    right: 5,
    top: 4,
  },

  shareReferModalView: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  shareReferModalContainer: {
    backgroundColor: 'white',
    width: '90%',
    borderRadius: 8,
    padding: 10,
  },
  shareTitle: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    borderBottomWidth: 0.5,
  },
  shareTitleText: {
    width: '90%',
    fontSize: 15,
    fontWeight: '600',
    color: 'black',
  },
  shareModalCloseIcon: {
    width: 20,
    height: 20,
    marginBottom: 32,
  },
  referLinkView: {
    width: '100%',
    height: 40,
    borderWidth: 0.5,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    // borderColor: '#F8931D',
    paddingHorizontal: 8,
    marginVertical: 15,
    // backgroundColor: 'red',
  },
  copyImg: {
    width: 20,
    height: 20,
  },
  referLink: {
    color: 'black',
    fontSize: 15,
  },
  socialIconsView: {
    marginTop: 10,
    flexDirection: 'row',
    // backgroundColor: 'red',
    width: '90%',
    justifyContent: 'space-around',
    alignSelf: 'center',
  },
  socialIcons: {
    // color: '#F8931D',
    color: '#ef5a24',
  },
  customImportedIcon: {
    width: 27,
    height: 27,
    tintColor: '#F8931D',
  },
  diractionView: {flexDirection: 'row', alignItems: 'center'},
  imageOffer: {width: 16, height: 15},
  availableText: {
    color: '#000000',
    fontSize: 14,
    fontWeight: '400',
    marginLeft: 3,
  },
  boxOffer: {
    backgroundColor: '#d8ffdccc',
    borderWidth: 0.5,
    borderColor: '#2A7A21',
    borderRadius: 8,
    padding: 4,
    paddingHorizontal: 4,
    flexDirection: 'row',
    marginTop: 4,
    flex: 1,

    width: 'auto',
    maxWidth: 350,
    // width: '36%',
  },
  dot: {fontSize: 16, color: '#007626', bottom: 3},
  discrapton: {
    fontSize: 12,
    color: '#007626',
    textAlign: 'left',
    marginLeft: 4,
  },
  rewardWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 5,
  },
  rewardIcon: {
    width: 20,
    height: 20,
    marginRight: 3,
  },
  rewardPoints: {
    color: '#282828',
  },
});
