import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

const styles = StyleSheet.create({
  font13: {
    fontSize: 13,
    lineHeight: 22,
  },
  fontBold: {
    fontWeight: 'bold',
  },
  pageContainer: {
    flex: 1,
    backgroundColor: '#f2f2f2',
    zIndex: -1,
  },
  tabContainer: {
    flexDirection: 'row',
    marginHorizontal: wp('5%'),
  },
  singleTab: {
    flex: 1,
    paddingVertical: hp('2%'),
    justifyContent: 'center',
    alignItems: 'center',
  },
  singleTabText: {
    fontSize: 16,
    fontWeight: '400',
  },
  selectedTabText: {
    fontWeight: 'bold',
  },
  selectedTab: {
    borderBottomWidth: 2,
    borderColor: '#f50157',
  },

  sectionsContainer: {
    flex: 1,
  },
  itemTermButtonContainer: {
    backgroundColor: '#FFF',
    marginTop: hp('2%'),
    borderRadius: hp('1%'),
    paddingHorizontal: wp('3%'),
    paddingVertical: hp('3%'),
  },
  itemsSectionHeaderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  itemsSectionHeaderText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  termConditionContainer: {
    // marginTop: hp('3%'),
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: -1,
  },
  termConditionText: {
    marginLeft: wp('3%'),
    fontSize: 14,
    fontWeight: 'bold',
    color: '#cc1c1c',
    textDecorationLine: 'underline',
  },
  attachmentContainer: {
    marginTop: hp('2%'),
    backgroundColor: '#FFF',
    borderRadius: hp('1%'),
    padding: hp('2%'),
  },
  allImagesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  imageContainer: {
    height: wp('20%'),
    width: wp('20%'),
    borderRadius: wp('2%'),
    borderWidth: 1,
    borderColor: '#cccccc',
    // marginLeft: wp('5%'),
    // marginBottom: hp('3%'),
  },
  imageContainerClose: {
    position: 'absolute',
    backgroundColor: '#00a8f4',
    borderRadius: wp('20%'),
    right: -wp('2.5%'),
    top: -wp('2.5%'),
    padding: wp('.5%'),
  },
  attachmentButtonContainer: {
    padding: hp('2%'),
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#c2cfdf',
    borderRadius: hp('0.5%'),
    shadowColor: '#c2cfdf',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,

    elevation: 24,
  },
  buttonContainer: {
    width: wp('30%'),
    flexDirection: 'row',
    backgroundColor: '#f3933e',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp('2%'),
    marginTop: hp('3%'),
    zIndex: -1,
  },
  buttonDisabled: {
    backgroundColor: '#e8e6e6',
  },
  buttonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalView: {
    width: '100%',
    backgroundColor: 'white',
    borderRadius: hp('1%'),
    // height: '100%',
    // shadowColor: '#000',
    // shadowOffset: {
    //   width: 0,
    //   height: 2,
    // },
    // shadowOpacity: 0.25,
    // shadowRadius: 4,
    // elevation: 5,
  },
  modalTitleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingStart: wp('3%'),
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    paddingVertical: hp('1.5%'),
  },
  modalTitleText: {
    flex: 1,
    fontSize: 20,
    fontWeight: 'bold',
    color: 'rgba(0, 0, 0, 0.87)',
  },
  modalCloseContainer: {
    paddingVertical: hp('1.5%'),
    paddingHorizontal: wp('3%'),
  },
  modalDescContainer: {
    marginVertical: hp('2%'),
    marginHorizontal: wp('3%'),
  },
  modalDescText: {
    fontSize: 16,
    lineHeight: 22,
  },
  itemRenderContainer: {
    marginVertical: hp('2%'),
  },
  itemHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  itemHeaderImageContainer: {
    height: wp('15%'),
    width: wp('15%'),
    borderRadius: wp('10%'),
    backgroundColor: '#f7f7f7',
    borderWidth: 1,
    borderColor: '#efefef',
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemHeaderText: {
    flex: 1,
    marginHorizontal: wp('5%'),
    fontSize: 14,
    fontWeight: 'bold',
  },
  inputContainer: {
    marginTop: hp('2%'),
    borderWidth: 1,
    borderRadius: hp('1%'),
    borderColor: '#cccccc',
    height: hp('6%'),
    paddingHorizontal: wp('3%'),
  },
  returnItemsRenderContainer: {
    backgroundColor: '#FFF',
    marginVertical: hp('2%'),
  },
  returnItemsRenderHeaderContainer: {
    paddingVertical: hp('3%'),
    paddingHorizontal: wp('3%'),
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  returnItemsRenderHeaderText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  itemHeaderImage: {
    height: wp('12%'),
    width: wp('12%'),
    borderRadius: wp('10%'),
  },
  returnItemRenderItemsContainer: {
    flexDirection: 'row',
    marginHorizontal: wp('3%'),
    alignItems: 'center',
    marginVertical: hp('3%'),
  },
  returnItemRenderItemsDataContainer: {
    marginLeft: wp('3%'),
    flex: 1,
  },
  loaderContainer: {
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
    zIndex: 10,
  },
  emptyComponent: {
    paddingVertical: hp('7%'),
    paddingHorizontal: wp('10%'),
    justifyContent: 'center',
    alignItems: 'center',
  },
  textAreaContainer: {
    borderWidth: 1,
    height: hp('10%'),
    borderRadius: hp('1%'),
    paddingHorizontal: wp('3%'),
    paddingTop: hp('1.5%'),
    paddingBottom: hp('1.5%'),
    borderColor: '#cccccc',
    marginBottom: hp('3%'),
  },
  selectedProductView: {
    backgroundColor: 'white',
    marginTop: hp('0.5%'),
    padding: wp('2.5%'),
  },
  selectedProductText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#464545',
  },
  productListView: {
    backgroundColor: 'white',
    marginTop: hp('1%'),
    flex: 1,
  },
  bodyWithList: {
    paddingHorizontal: wp('2.5%'),
    paddingTop: wp('2.5%'),
    flex: 1,
  },
  imageBox: {
    width: 40,
    height: 40,
    borderWidth: 0.5,
    borderRadius: 4,
    borderColor: 'grey',
    justifyContent: 'center',
    alignItems: 'center',
  },
  quantityView: {
    padding: 6,
    // width: '100%',
    borderWidth: 0.6,
    // height: 30,
    borderRadius: 2,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    // paddingHorizontal: 40,
    // marginTop: 4,
  },
  dropdown: {
    // bottom: 0,
    borderWidth: 0.6,
    borderRadius: 2,
    paddingHorizontal: 10,
    // backgroundColor: 'green',
    // paddingHorizontal: 20,
    // height: 20,
    // width: '40%',
    // backgroundColor: 'red',
  },
  placeholderStyle: {
    paddingHorizontal: 6,
  },
  attachmentView: {
    marginTop: 5,
    alignItems: 'center',
    // width: '%',
    // height: '40%',
    padding: 30,

    borderWidth: 0.5,
  },
  thumbsUpVIew: {
    alignSelf: 'center',
    alignItems: 'center',
  },
  submittedText: {
    marginTop: 10,
    color: '#464545',
    fontSize: 15,
    fontWeight: '700',
  },
  requestText: {
    marginTop: 5,
    // color: '#767676',
    width: '70%',
  },
  myReturnBtn: {
    backgroundColor: '#F3943D',
    width: '45%',
    alignSelf: 'center',
    marginTop: 20,
    alignItems: 'center',
    padding: 8,
    borderRadius: 2,
  },
  texts: {
    flexDirection: 'row',
    paddingHorizontal: 10,
    marginTop: 10,
  },
  seprater: {
    width: '92%',
    alignSelf: 'center',
    borderWidth: 0.7,
    borderColor: 'grey',
    marginVertical: 20,
  },
  allText: {
    // marginTop: 10,
    color: '#464545',
    fontSize: 15,
    fontWeight: '700',
  },
  allProductView: {
    borderWidth: 0.7,
  },
  allProductSubView: {
    borderBottomWidth: 0.7,
    padding: 10,
  },
  saveFormBtn: {
    backgroundColor: '#F3943D',
    width: '45%',
    alignSelf: 'center',
    marginTop: 20,
    alignItems: 'center',
    padding: 8,
    borderRadius: 2,
  },
  subReqBtn: {
    backgroundColor: '#F3943D',
    width: '100%',
    alignSelf: 'center',
    alignItems: 'center',
    padding: 8,
    borderRadius: 2,
  },
});

export default styles;
