// export { default as GET_CART_QUERY } from './queries/get_cart.gql';
export {default as GET_CAROUSEL_PRODUCTS_QUERY} from './queries/get_carousel_products.gql';
export {default as ADD_TO_CART_QUERY} from './mutations/add_to_cart.gql';
// export { default as UPDATE_CART_ITEM_QUERY } from './mutations/update_cart_item.gql';
// export { default as REMOVE_CART_ITEM_QUERY } from './mutations/remove_cart_item.gql';
// export { default as APPLY_COUPON_QUERY } from './mutations/apply_coupon.gql';
// export { default as REMOVE_COUPON_QUERY } from './mutations/remove_coupon.gql';
export {default as ADD_SIMPLE_PRODUCT_TO_CART_MUTATION} from './mutations/simple_product_mutation.gql';
export {default as ADD_VIRTUAL_PRODUCT_TO_CART} from './mutations/addVirtualProductToCart.gql';
export {default as ADD_GROUP_PRODUCTS_TO_CART_MUTATION} from './mutations/add_group_product_to_cart.gql.js';
export {default as ADD_MULTIPLE_PRODUCTS_TO_CART} from './mutations/add_multiple_items_to_cart.gql.js';
export {default as ADD_CONFIGURABLE_PRODUCT_TO_CART_MUTATION} from './mutations/add_configurable_products_to_cart.gql.js';
export {default as ADD_BUNDLE_PRODUCT_TO_CART_MUTATION} from './mutations/add_bundle_product_to_cart.gql.js';
export {default as GET_GUEST_CART_ID} from './mutations/empty_cart_mutation.gql.js';
export {default as GET_CUSTOMER_CART_ID} from './mutations/customer_cart.gql.js';
export {default as GET_NEW_CART} from './queries/get_new_cart.gql';
export {default as GUEST_NEW_CART} from './queries/guest_new_cart.gql';
export {default as GET_MERGE_CART} from './mutations/merge_cart_mutation.gql.js';
export {default as REMOVE_CART_ITEM} from './mutations/remove_cart_item.gql.js';
export {default as UPDATE_CART_ITEM} from './mutations/update_cart_item.gql.js';
export {default as APPLY_COUPON_MUTATION} from './mutations/apply_coupon_to_cart.gql.js';
export {default as REMOVE_COUPON_MUTATION} from './mutations/remove_coupon_from_cart.gql.js';
export {default as GET_CUSTOMER_COUPONS} from './queries/customer_coupons.gql.js';
export {default as CHECK_COD_AVAILABILITY} from './queries/check_cod_availability.gql.js';
export {default as GET_AVAILABLE_PAYMENT_METHOD} from './queries/get_available_methods.gpl.js';
export {default as WEIGHT_SLAB_FOR_COUNTRIES} from './queries/weight_slab_for_countries.gql';
export {default as SET_SHIPPING_ADDRESS_ON_CART} from './mutations/setShippingAddressOnCart.gql';
export {default as GET_PROMOTION_BY_CART_VALUE} from './queries/promotionByCartValue.gql.js';
