import {StyleSheet, Platform} from 'react-native';
import {DeviceWidth, SecondaryColor, PrimaryColor} from '@config/environment';
import colors from '@config/colors';
export default sttyles = StyleSheet.create({
  similarProductSubView: {
    height: '100%',
    backgroundColor: colors.white,
    paddingLeft: 20,
    paddingVertical: 5,
    justifyContent: 'center',
  },
  youalsoLikeText: {
    paddingVertical: 7,
    paddingHorizontal: 20,
    backgroundColor: colors.white,
    alignContent: 'center',
    top: 0,
  },
  couponeCodeView: {
    height: 50,
    paddingVertical: 5,
    backgroundColor: colors.HexColor,
  },
  couponeSubView: {
    height: 40,
    backgroundColor: colors.white,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: 20,
  },
  cartItemOfferView: {
    width: 89,
    height: 38,
    borderRadius: 5,
    backgroundColor: colors.HexColor,
    justifyContent: 'center',
    paddingHorizontal: 3,
  },
  modalMainView: {
    width: '100%',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stockOutModalEmptyView: {
    flex: 0.25,
    width: '100%',
    backgroundColor: '#253541',
    opacity: 0.5,
  },
  StockOutProView: {
    height: 160,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  StockOutProimgView: {
    width: '23%',
    height: 120,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.otpBorder,
  },
  StockOutDisView: {
    width: '65%',
    height: 120,
    justifyContent: 'center',
    paddingLeft: 20,
  },
  StockOutDisText: {fontSize: 15, color: colors.black, height: 25},
  StockOutText: {
    height: 25,
    color: colors.black,
    alignContent: 'center',
    fontSize: 17,
  },
  StockOutmodalSubView: {
    height: 100,
    backgroundColor: colors.HexColor,
    paddingHorizontal: 20,
    paddingVertical: 8,
    justifyContent: 'space-around',
  },
  similarProductMainView: {
    height: 180,
    paddingVertical: 4,
    backgroundColor: colors.HexColor,
  },
  similarProductSubView: {
    height: '100%',
    backgroundColor: colors.white,
    paddingLeft: 20,
    paddingVertical: 5,
    justifyContent: 'center',
  },
  notifyText: {color: colors.blueColor, fontSize: 18},
  notifyView: {
    flex: 0.4,
    height: '100%',
    backgroundColor: colors.AliceBlue,
    justifyContent: 'center',
    alignItems: 'center',
  },
  norecomendationsView: {
    flex: 0.6,
    height: '100%',
    backgroundColor: colors.orangeBtn,
    justifyContent: 'center',
    alignItems: 'center',
  },
  StockOutFooterBtnView: {
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  unavilableText: {fontSize: 13, color: colors.white},
  unavilableView: {
    width: 130,
    height: 35,
    borderRadius: 20,
    backgroundColor: '#FF4F4F',
    justifyContent: 'center',
    alignItems: 'center',
  },
  footerBtnView: {
    height: 55,
    marginVertical: 9,
    backgroundColor: colors.SummerSky,
    justifyContent: 'center',
    alignItems: 'center',
  },
  priceIcon: {fontSize: 16, color: colors.blueColor},
  priceView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginTop: 5,
  },
  priceText: {fontSize: 16, color: colors.blueColor, fontWeight: 'bold'},
  productMappingView: {
    width: 120,
    height: '95%',
    marginTop: 5,
    marginHorizontal: 8,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 4,
  },
  productMappingImg: {
    height: '40%',
    width: '90%',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.HexColor,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dissVIew: {height: '40%', width: '100%', marginTop: 5, paddingHorizontal: 5},
  productDiss: {fontSize: 12, color: '#001733', paddingVertical: 3},
  productMappingPriceMainView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginVertical: 5,
    paddingLeft: 10,
  },
  dispriceView: {
    width: '40%',
    height: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dispriceTxt: {
    fontSize: 12,
    color: colors.Sundown,
    textDecorationLine: 'line-through',
  },
  rupeeIcon: {
    fontSize: 9,
    color: colors.Sundown,
    textDecorationLine: 'line-through',
  },
  modalSubView: {flex: 0.75, width: '100%', backgroundColor: colors.white},
  eitherTxt: {
    color: colors.LightSlateGrey,
    alignContent: 'center',
    fontSize: 14,
  },
  dispersible: {fontSize: 13, color: colors.LightSlateGrey},
  norecomendationTxt: {color: colors.white, fontSize: 15},
  removeBtnTxt: {color: colors.white, fontSize: 17},
});
