import {StyleSheet, Dimensions} from 'react-native';
import {DeviceWidth, PrimaryColor, SecondaryColor} from '@config/environment';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import colors from '@config/colors';
// import { screenPadding, moderateScale, writeLog, verticalScale, responsiveHeight, responsiveFontSize, responsiveWidth } from '@config/functions';
const styles = StyleSheet.create({
  orderIdWrapper: {
    padding: 10,
  },
  loader: {
    // flex: 1,
    alignItems: 'center',
    // flexDirection: 'column',
    justifyContent: 'center',
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'red',
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 3,
    marginVertical: 5,
    marginHorizontal: 8,
    elevation: 1,
    shadowColor: '#bfbfbf',
    shadowOffset: {
      height: 0,
      width: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 2,
  },
  productImageWrapper: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: DeviceWidth / 3,
  },
  productImage: {
    width: 60,
    height: 60,
  },
  productDetailWrapper: {
    width: DeviceWidth - DeviceWidth / 3,
  },
  imageDetailsWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 5,
  },
  productIndex: {
    color: '#21212150',
    fontSize: 12,
  },
  productDetailValue: {
    color: '#212121',
  },
  customizedProductDetailWrapper: {
    flexDirection: 'row',
  },
  customizedProductDetails: {
    color: '#21212180',
    fontSize: 12,
  },
  cardHeader: {
    borderBottomColor: '#ddd',
    padding: 5,
    borderBottomWidth: 0.5,
  },
  header: {
    color: '#212121',
  },
  cardBodyWrapper: {
    padding: 5,
  },
  twoFields: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 7,
  },
  field: {
    color: '#21212180',
  },
  cancelButtonWrapper: {
    backgroundColor: PrimaryColor,
    margin: 7,
    borderRadius: 3,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelButton: {
    color: '#fff',
    fontSize: 14,
  },
  productShipmentContainer: {
    marginVertical: 15,
    elevation: 1.5,
    shadowColor: '#bfbfbf',
    shadowOffset: {
      height: 1,
      width: 1,
    },
    shadowOpacity: 1,
    shadowRadius: 5,
    backgroundColor: '#fff',
  },
  productsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  shipmentCardHeading: {
    color: SecondaryColor,
    fontSize: 14,
  },
  trackButton: {
    alignItems: 'center',
    margin: 10,
    borderRadius: 3,
    borderColor: SecondaryColor,
    borderWidth: 1,
  },
  trackButtonText: {
    color: '#fff',
    fontSize: 14,
    lineHeight: 14,
  },
  rewardWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rewardIcon: {
    width: 18,
    height: 18,
  },
  rewardPoints: {
    color: '#282828',
  },
  rewardsInfoCard: {
    flex: 1,
    flexDirection: 'row',
    padding: 5,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 1,
    marginBottom: 5,
    backgroundColor: '#fff',
    marginHorizontal: 8,
    shadowColor: '#bfbfbf',
    shadowOffset: {
      height: 0,
      width: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 2,
  },
  rewardPointsContainer: {
    alignItems: 'center',
    flex: 1,
  },
  pointsWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 15,
    marginVertical: 5,
  },
  borderRight: {
    borderRightColor: '#efefef',
    borderRightWidth: 1,
  },

  orderSummarySUbView: {
    marginTop: 8,
    width: '100%',
    backgroundColor: '#fff',
    paddingHorizontal: 15,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  orderAddressView: {
    marginTop: 8,
    width: '100%',
    backgroundColor: '#fff',
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  orderSummaryText: {fontSize: 14, color: '#000'},
  orderStatusColor: {color: colors.orangeBtn},
  orderAddressText: {fontSize: 15, fontWeight: '500', color: '#000'},
  moadlWhiteBgView: {
    marginTop: 8,
    width: '100%',
    minHeight: 52,
    paddingBottom: 10,
    backgroundColor: colors.white,
    paddingHorizontal: 15,
    marginBottom: 8,
  },
  packTextMainView: {
    width: '100%',
    height: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  packageImgView: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemCountView: {
    width: 100,
    height: 25,
    borderRadius: 15,
    backgroundColor: colors.HexColor,
    justifyContent: 'center',
    alignItems: 'center',
    right: 5,
  },
  downloadButton: {
    flexDirection: 'row',
    width: 100,
    height: 25,
    borderRadius: 15,
    backgroundColor: colors.HexColor,
    justifyContent: 'center',
    alignItems: 'center',
    right: 5,
  },
  itemCountText: {fontSize: 11, fontWeight: '400', color: colors.black},
  trackingTxtView: {
    width: '100%',
    height: 30,
    justifyContent: 'center',
    paddingHorizontal: 5,
  },
  trackingTxt: {fontSize: 13, color: colors.productHeaderText},
  deliveryTxtView: {
    width: '100%',
    height: 30,
    bottom: 1,
    justifyContent: 'center',
    paddingHorizontal: 5,
  },
  deliveryTxt: {fontSize: 12.5, color: colors.black},
  btnView: {
    width: '100%',
    height: 42,
    justifyContent: 'center',
    flexDirection: 'row',
    paddingHorizontal: 5,
  },
  trakBtn: {
    width: '40%',
    height: 35,
    borderRadius: 3,
    backgroundColor: colors.SummerSky,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: wp('4%'),
  },
  cancelBtn: {
    width: wp('35%'),
    height: 35,
    borderRadius: 3,
    backgroundColor: colors.SummerSky,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelBtnDisable: {
    width: wp('35%'),
    height: 35,
    borderRadius: 3,
    backgroundColor: colors.SummerSkyLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardLeftButtonContainer: {
    width: '40%',
    height: 35,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: hp('1.1%'),
    borderRadius: hp('.5%'),
    borderColor: colors.borderColor,
    marginRight: wp('4%'),
  },
  cardLeftButtonText: {color: colors.black, fontSize: 14, lineHeight: 14},
  address: {
    fontSize: 11.5,
    color: '#9d9d9d',
    fontWeight: '400',
    width: '50%',
    lineHeight: 15,
  },
  priceDetailView: {
    height: 45,
    backgroundColor: colors.white,
    justifyContent: 'center',
    paddingHorizontal: 20,
    marginBottom: 2,
  },
  priceDetailText: {color: colors.black, fontWeight: '600', fontSize: 15},
  billMainView: {
    minHeight: 40,
    backgroundColor: colors.white,
    justifyContent: 'center',
    paddingHorizontal: 20,
    marginBottom: 2,
    paddingVertical: 10,
  },
  itemView: {
    width: '100%',
    minHeight: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  itemText: {fontSize: 13, color: colors.black, paddingVertical: 5},
  itemTextCount: {
    fontSize: 16,
    color: colors.blueColor,
    textAlign: 'right',
    right: 0,
  },
  rewardsPointsView: {
    height: 70,
    backgroundColor: colors.white,
    paddingHorizontal: 20,
    justifyContent: 'space-evenly',
    marginBottom: 8,
  },
  rewardsPointsText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.black,
    top: 7,
  },
  earnedView: {
    flexDirection: 'row',
    minWidth: 40,
    alignItems: 'center',
    height: '50%',
  },
  refetchContainerView: {
    position: 'absolute',
    height: '100%',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  refetchView: {
    backgroundColor: '#FFF',
    borderRadius: 5,
    width: '80%',
    paddingVertical: 50,
    alignSelf: 'center',
    alignItems: 'center',
  },
  pdf: {
    flex: 1,
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
  cancelOrderModel: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelOrderModelContainer: {
    minHeight: 130,
    backgroundColor: '#fff',
    borderRadius: 10,
    width: '90%',
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  cancelOrderModelHeading: {
    paddingBottom: 10,
    alignItems: 'center',
  },
  modalTitle: {
    color: '#000',
    fontSize: 18,
    fontWeight: '500',
  },
  modalSubTitle: {
    color: '#000',
    fontSize: 14,
  },
  modalButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  yesNoText: {
    color: '#fff',
    fontSize: 14,
  },
  separator: {
    backgroundColor: '#C6D2DE',
    height: 0.4,
  },
  ItemContainer: {
    paddingVertical: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  regNoContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  regNoText: {
    color: '#000',
    fontSize: 14,
    paddingVertical: 4,
    paddingRight: 5,
    paddingLeft: 5,
    maxWidth: 200,
  },
  itemDeliveredList: {
    fontSize: 12,
    fontWeight: '600',
  },
  flexRowSpace: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  orderTotalText: {
    fontWeight: '600',
    fontSize: 12,
  },
});
export default styles;
