require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
target 'dentalkartnative' do
  config = use_native_modules!


  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  
  pod 'react-native-appsflyer', :path => '../node_modules/react-native-appsflyer'
  
  pod 'Firebase/Core', '~> 6.13.0'
  pod 'Firebase/Messaging', '~> 6.13.0'
  pod 'GoogleSignIn', '~> 5.0.2'
  pod 'Protobuf', '3.21.12'
  pod 'AppAuth', '1.2.0'
#  pod 'WebEngage'
  pod 'BEMCheckBox'

  pod 'react-native-webengage', :path => '../node_modules/react-native-webengage'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'dentalkartnativeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!()
#  post_install do |installer|
#    flipper_post_install(installer)
#  end



    post_install do |installer|
      react_native_post_install(installer)
      __apply_Xcode_12_5_M1_post_install_workaround(installer)
      installer.pods_project.build_configurations.each do |config|
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
          end
    end
  end

