const headerConfiguration = {
  default: {
    params: {topSection: false, bottomSection: false, backHeader: true},
    icons: {
      drawer: false,
      search: false,
      cart: false,
      logo: true,
      auth: false,
      currency: false,
      reward: false,
    },
  },
  home: {
    params: {topSection: true, bottomSection: true, backHeader: false},
    icons: {
      drawer: true,
      search: false,
      cart: true,
      logo: false,
      auth: true,
      currency: false,
      reward: false,
    },
  },
  navigation: {
    params: {topSection: false, bottomSection: false, backHeader: true},
    icons: {
      drawer: false,
      search: true,
      cart: true,
      logo: true,
      auth: false,
      currency: false,
      reward: false,
    },
  },
  category: {
    params: {topSection: false, bottomSection: false, backHeader: true},
    icons: {
      drawer: false,
      search: true,
      cart: true,
      logo: true,
      auth: false,
      currency: false,
      reward: false,
    },
  },
  product: {
    params: {topSection: false, bottomSection: false, backHeader: true},
    icons: {
      drawer: false,
      search: true,
      cart: true,
      logo: true,
      auth: false,
      currency: false,
      reward: false,
    },
  },
  writeReview: {
    params: {topSection: false, bottomSection: false, backHeader: true},
    icons: {
      drawer: false,
      search: true,
      cart: true,
      logo: true,
      auth: false,
      currency: false,
      reward: false,
    },
  },
  brands: {
    params: {topSection: false, bottomSection: false, backHeader: true},
    icons: {
      drawer: false,
      search: false,
      cart: false,
      logo: false,
      auth: false,
      currency: false,
      reward: false,
    },
  },
  productReviews: {
    params: {topSection: false, bottomSection: false, backHeader: true},
    icons: {
      drawer: false,
      search: true,
      cart: true,
      logo: true,
      auth: false,
      currency: false,
      reward: false,
    },
  },
  cart: {
    params: {topSection: false, bottomSection: false, backHeader: true},
    icons: {
      drawer: false,
      search: false,
      cart: false,
      logo: true,
      auth: true,
      currency: false,
      reward: false,
    },
  },
  payment: {
    params: {topSection: false, bottomSection: false, backHeader: true},
    icons: {
      drawer: false,
      search: false,
      cart: false,
      logo: true,
      auth: false,
      currency: false,
      reward: false,
    },
  },
  login: {
    params: {topSection: false, bottomSection: false, backHeader: true},
    icons: {
      drawer: false,
      search: false,
      cart: false,
      logo: true,
      auth: false,
      currency: false,
      reward: false,
    },
  },
  account: {
    params: {topSection: false, bottomSection: false, backHeader: true},
    icons: {
      drawer: false,
      search: false,
      cart: false,
      logo: true,
      auth: false,
      currency: false,
      reward: false,
    },
  },
  country: {
    params: {topSection: false, bottomSection: false, backHeader: true},
    icons: {
      drawer: false,
      search: false,
      cart: false,
      logo: true,
      auth: false,
      currency: false,
      reward: false,
    },
  },
  help: {
    params: {topSection: false, bottomSection: false, backHeader: true},
    icons: {
      drawer: false,
      search: false,
      cart: false,
      logo: true,
      auth: false,
      currency: false,
      reward: false,
    },
  },
  wishlist: {
    params: {topSection: false, bottomSection: false, backHeader: true},
    icons: {
      drawer: false,
      search: false,
      cart: false,
      logo: true,
      auth: true,
      currency: false,
      reward: false,
    },
  },
};
export default headerConfiguration;
