import {StyleSheet, Dimensions} from 'react-native';

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
import {SecondaryColor, DeviceWidth} from '@config/environment';
import colors from '@config/colors';
export default styles = StyleSheet.create({
  // containerWrapper:{
  //     marginRight: 8,
  //     marginLeft: 8,
  // },
  addressCard: {
    backgroundColor: '#fff',
    padding: 10,
    marginBottom: 3,
    textAlign: 'justify',
    width: '100%',
    minHeight: 10,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    paddingVertical: 3,
    borderBottomWidth: 1,
    marginTop: 7,
    borderBottomColor: '#EBF0FF',
  },
  linkText: {
    paddingVertical: 5,
    // textDecorationLine: "underline",
    textDecorationStyle: 'solid',
    color: '#000',
  },
  activeCard: {
    backgroundColor: '#fff8ea',
  },
  addressMainView: {
    height: '100%',
    backgroundColor: colors.white,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  addressIconView: {
    width: '10%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addressIconsubView: {
    width: 20,
    height: 20,
    borderRadius: 20,
    backgroundColor: colors.PattensBlue,
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationIcon: {fontSize: 12, color: '#365F71'},
  addressView: {minHeight: 70, width: '90%'},
  addressCount: {fontSize: 18, color: '#000', fontWeight: 'bold'},
  address: {fontSize: 14, color: colors.normalText},
  defaultAddressTxt: {
    fontWeight: 'bold',
    lineHeight: 15,
    marginTop: 15,
    fontSize: 13,
  },
  modalMainView: {
    flex: 1,
    width: '100%',
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addressModalView: {
    width: '95%',
    // minHeight: 400,
    backgroundColor: '#fff',
    borderRadius: 8,
    paddingBottom: 5,
  },
  modalHeaderView: {
    width: '100%',
    flex: 0.1,
    borderBottomWidth: 5,
    justifyContent: 'center',
    paddingHorizontal: 15,
    flexDirection: 'row',
    borderBottomColor: colors.HexColor,
  },
  locationTxtView: {width: '80%', height: '100%', justifyContent: 'center'},
  locationTxt: {fontSize: 18, fontWeight: '700'},
  closeIconView: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'flex-end',
    position: 'absolute',
    right: 8,
    // bottom: '20%',
    // alignSelf: 'flex-end',
    // backgroundColor: 'red',
    // alignItems: 'flex-end',
    top: 0,
  },
  closeIcon: {fontSize: 18, color: '#2b79ac'},
  midView: {
    width: '100%',
    flex: 0.9,
    justifyContent: 'center',
    flexDirection: 'row',
    paddingBottom: 3,
  },
  enterpinCodeTxt: {
    marginTop: 5,
    marginBottom: 5,
    marginLeft: 8,
    textAlign: 'center',
  },
  deliveryView: {
    width: '90%',
    height: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  addressTouchable: {display: 'flex', flexDirection: 'row'},
  shadow: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: Platform.OS == 'android' ? 3 : 1.5,
    },
    shadowOpacity: 0.35,
    shadowRadius: 2,
    elevation: Platform.OS == 'android' ? 3 : 1,
  },
  addressBox: {
    width: 180,
    height: 160,
    margin: 10,
    borderRadius: 6,
    backgroundColor: '#fff',
    paddingHorizontal: 10,
  },
  PhoneIcon: {fontSize: 18, color: colors.blueColor},
  AddShippingAddresssMainView: {
    width: '100%',
    height: 60,
    backgroundColor: colors.HexColor,
    justifyContent: 'center',
    alignItems: 'center',
  },
  AddShippingAddresssView: {
    width: '100%',
    height: 50,
    backgroundColor: '#fff',
    justifyContent: 'center',
    paddingHorizontal: 5,
    top: 5,
  },
  orEnterView: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  orEnterTxt: {fontSize: 15, color: '#aaa', fontWeight: '700'},
  addressSubView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  addressIconMainView: {width: '15%', height: 50, top: 5},

  //new MOdal
  MainModalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
  },
  ModalContainer: {
    width: '95%',
    backgroundColor: 'white',
    alignSelf: 'center',
    borderRadius: 8,
  },
  underContainer: {
    width: '90%',
    alignSelf: 'center',
  },
  Header: {
    marginTop: '1.5%',
    width: '100%',
    borderBottomWidth: 5,
    // paddingLeft: 15,
    flexDirection: 'row',
    borderBottomColor: colors.HexColor,
    justifyContent: 'space-between',
  },
  HeaderText: {
    fontSize: 18,
    fontWeight: '700',
  },
  closeIconView: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    position: 'absolute',
    marginLeft: '94%',
  },
  closeIcon: {fontSize: 18, color: '#2b79ac'},
  checkServiceAvailiblity: {
    marginTop: '2%',
  },
  serviceText: {
    fontSize: 13.5,
    fontWeight: 'bold',
    marginLeft: 2,
    marginBottom: 5,
  },
  checkServiceInput: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 2,
    width: '100%',
    justifyContent: 'center',
  },
  CheckServiceInputField: {
    borderWidth: 0.5,
    borderColor: colors.borderColor,
    paddingLeft: 10,
    height: 40,
    width: DeviceWidth - 165,
    padding: 4,
    marginHorizontal: 2,
    fontSize: 14,
    marginRight: 10,
    borderRadius: 3,
  },
  CheckServiceButton: {
    width: 100,
    height: 38,
    elevation: 4,
    backgroundColor: SecondaryColor,
    borderRadius: 3,
    justifyContent: 'center',
    alignItems: 'center',
  },
  CheckServiceButtonText: {
    color: '#fff',
  },
  pincodeView: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 8,
  },
  MUIcon: {
    paddingRight: 8,
  },
  pincodeCheckTexts: {
    color: '#1c60dc',
  },
  orView: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: '1.5%',
  },
  orTxt: {fontSize: 15, color: '#aaa', fontWeight: '700'},
  addressBoxx: {
    width: 180,
    margin: 10,
    borderRadius: 6,
    backgroundColor: '#fff',
    paddingHorizontal: 10,
    borderWidth: 0.3,
    borderColor: 'grey',
  },
  shadoww: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: Platform.OS == 'android' ? 3 : 1.5,
    },
    shadowOpacity: 0.35,
    shadowRadius: 2,
    elevation: Platform.OS == 'android' ? 3 : 1,
  },
  addressSubView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  addressIconMainView: {width: '15%', height: 50, top: 5},
  linkTextt: {
    textDecorationLine: 'underline',
    // color: '#2a5db0',
    color: colors.blueColor,
    fontWeight: 'bold',
  },
  loginView: {
    marginTop: '2%',
  },
  countryPicker: {
    width: '100%',
    alignSelf: 'center',
    borderWidth: 0.5,
    borderColor: 'grey',
    marginBottom: '3%',
  },
  pinError: {
    color: 'red',
  },

  //extraaaaaaa modelll

  modalWrapper: {
    width: '100%',
    position: 'absolute',
    bottom: 0,
    backgroundColor: '#fff',
    paddingTop: 15,
    paddingBottom: 15,
    paddingLeft: 20,
    paddingRight: 20,
    borderTopColor: '#ddd',
    borderWidth: 0.5,
    shadowColor: '#bfbfbf',
    shadowOpacity: 0.5,
    shadowOffset: {
      height: 0,
      width: 0,
    },
    elevation: 1,
    zIndex: 2,
  },
  modalCloseButton: {
    paddingTop: 4,
    paddingBottom: 4,
    paddingLeft: 10,
    paddingRight: 8,
    borderRadius: 12,
    backgroundColor: SecondaryColor,
    color: '#fff',
    textAlign: 'center',
    width: 130,
    marginTop: 10,
  },
  expiryInfohead: {
    borderWidth: 1,
    borderColor: '#ddd',
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 10,
    paddingRight: 10,
    flexDirection: 'row',
  },
  info_text: {
    flexDirection: 'row',
  },
  linkTexttt: {
    textDecorationLine: 'underline',
    color: '#2a5db0',
  },
  iButton: {
    paddingLeft: 5,
    paddingTop: 3,
  },
  GroupHeadText: {
    marginRight: 5,
  },
  MainViewRetun: {
    flexDirection: 'row',paddingHorizontal:6
  },
  dotView: {
    paddingRight: '2%',
  },
  Footer: {
    flexDirection: 'row',
    padding: '2%',
    justifyContent: 'space-between',
  },
  filterSortContainer: {
    backgroundColor: '#fff',
    elevation: 10,
    shadowColor: '#bfbfbf',
    shadowOffset: {
      height: 0,
      width: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 2,
    justifyContent: 'center',
    position: 'absolute',
    bottom: 0,
  },
  filterSortWrapper: {
    flexDirection: 'row',
  },
  filterButtonWrapper: {
    width: DeviceWidth / 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterText: {
    fontSize: 15,
    color: '#212121',
  },
  sortButtonWrapper: {
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterButton: {
    width: DeviceWidth / 2,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 0.5,
    borderRightColor: '#5e5e5e',
    backgroundColor: '#ffffff',
    elevation: 1,
    shadowColor: '#bfbfbf',
    shadowOffset: {
      height: 0,
      width: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 2,
  },
  sortButton: {
    backgroundColor: '#fff',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#b9b9b9',
    elevation: 1,
    shadowColor: '#bfbfbf',
    shadowOffset: {
      height: 0,
      width: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 2,
  },
  sortButtonText: {
    color: '#212121',
    fontSize: 15,
  },
  modalHeaderr: {
    backgroundColor: SecondaryColor,
    height: 55,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  cartDelivery: {
    color: 'black',
  },
  terms: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: 6,paddingVertical:4
  },
 
  dot:{fontWeight:"bold",color:"#8D8D8D",fontSize:12,bottom:3},
  descraption :{fontWeight:"400",color:"#8D8D8D",fontSize:12,marginLeft:4},
  centeredView: {
    flex:1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor:"rgba(37, 53, 65, 0.85)",
  },
  modelView:{
    justifyContent: 'center',
    flex: 1,
    alignSelf: 'center',
    backgroundColor: 'rgba(37, 53, 65, 0.85)',
    width: '100%',
    alignItems: 'center',
  },
 modelSub:{
  backgroundColor: '#FFF',
  width: '90%',
  paddingVertical: 6,
  borderRadius: 8,
}

});
