import {StyleSheet, Platform} from 'react-native';
import {DeviceWidth, PrimaryColor, SecondaryColor} from '@config/environment';
import colors from '@config/colors';

export const Styles = StyleSheet.create({
  flatlistWrapper: {
    backgroundColor: '#fff',
  },
  loader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  contentWrapper: {
    flex: 1,
    backgroundColor: '#00000099',
    justifyContent: 'center',
    alignItems: 'center',
  },
  subView: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 10,
    elevation: 5,
    shadowColor: '#bfbfbf',
    shadowOffset: {
      height: 0,
      width: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 2,
    borderRadius: 3,
  },
  couponeCodeView: {
    height: 50,
    paddingVertical: 5,
    backgroundColor: colors.HexColor,
  },
  couponeSubView: {
    // backgroundColor: colors.white,
    justifyContent: 'space-between',
    // alignItems: 'center',
    flexDirection: 'row',
    paddingVertical: 10,
  },
  couponApplyButton: {
    fontSize: 12,
    color: colors.orangeBtn,
  },
  couponText: {
    color: '#1fa62d',
    fontSize: 13,
  },
  regNoText: {
    color: '#000',
    fontSize: 14,
    paddingVertical: 4,
    paddingRight: 5,
    paddingLeft: 5,
    maxWidth: 200,
  },
  saveAsDefaultText: {
    color: '#000',
    fontSize: 16,
    paddingVertical: 8,
    paddingTop: 8,
    paddingRight: 5,
  },
  regNoContainer: {
    flexDirection: 'row',
  },
  separator: {
    backgroundColor: '#C6D2DE',
    height: 0.4,
  },
  ItemContainer: {
    paddingVertical: 8,
  },
  IconsGrid: {
    flexDirection: 'row',
  },
  editIcon: {
    padding: 5,
  },
  closeIcon: {
    padding: 5,
    alignSelf: 'flex-end',
  },
  switchContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  regTextDanger: {
    color: '#ff0000',
    fontSize: 13,
  },
  changeButtonText: {
    color: '#ffffff',
    fontSize: 13,
  },
  changeButton: {
    backgroundColor: '#a52a2a',
    padding: 5,
    paddingHorizontal: 10,
    borderRadius: 3,
  },
  regNoDefault: {
    backgroundColor: '#60789c',
    padding: 5,
    paddingHorizontal: 10,
    borderRadius: 5,
  },
  regNoLabel: {
    fontSize: 13,
    color: '#292929',
    alignSelf: 'center',
  },
  regLabelWithNumber: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  deliveryAddressWrapper: {
    backgroundColor: '#fff',
    padding: 2,
    borderRadius: 3,
    marginTop: 8,
    marginBottom: 5,
    marginRight: 8,
    marginLeft: 8,
    elevation: 1,
    shadowColor: '#bfbfbf',
    shadowOffset: {
      height: 0,
      width: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 2,
  },
  nameWrapper: {
    paddingLeft: 10,
  },
  name: {
    fontSize: 14,
    textTransform: 'capitalize',
    marginBottom: 2,
  },
  addressDetailWrapper: {
    paddingLeft: 10,
  },
  addressText: {
    fontSize: 14,
    color: '#21212180',
  },
  buttonWrapper: {
    backgroundColor: '#fff',
    marginVertical: 5,
    marginHorizontal: 10,
    height: 30,
    borderWidth: 0.4,
    borderColor: SecondaryColor,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    elevation: 1.5,
    shadowColor: '#bfbfbf',
    shadowOffset: {
      height: 0,
      width: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 2,
  },
  buttonText: {
    color: SecondaryColor,
    fontSize: 13,
  },
  shortSummaryPrice: {
    fontSize: 15,
    color: '#212121',
  },
  continueButtonWrapper: {
    width: DeviceWidth / 2,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  methodWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 3,
    marginTop: 10,
  },
  paymentTitleWrapper: {
    width: DeviceWidth / 1.3,
  },
  paymentTitle: {
    fontSize: 14,
    color: '#21212190',
  },
  paymentRadioIconWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOff: {
    color: SecondaryColor,
  },
  placeOrderButton: {
    backgroundColor: PrimaryColor,
    width: DeviceWidth / 2,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 2,
    borderColor: '#b9b9b9',
    elevation: 1,
    shadowColor: '#bfbfbf',
    shadowOffset: {
      height: 0,
      width: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 2,
  },
  deliveryActionContainer: {
    backgroundColor: '#fff',
    elevation: 10,
    shadowColor: '#bfbfbf',
    shadowOffset: {
      height: 0,
      width: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 2,
    justifyContent: 'center',
  },
  deliveryActionWrapper: {
    flexDirection: 'row',
  },
  errorText: {
    paddingBottom: 10,
    alignItems: 'flex-start',
    alignSelf: 'flex-start',
  },
  shortSummaryWrapper: {
    width: DeviceWidth / 2,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  placeOrderButtonText: {
    color: '#fff',
    fontSize: 18,
  },
  paymentWrapper: {
    flex: 1,
    // alignItems: 'center',
    // justifyContent: 'center',
    padding: 8,
  },
  paymentHeading: {
    color: '#282828',
    paddingHorizontal: 8,
    paddingVertical: 5,
    fontSize: 14,
  },
  totalText: {
    color: '#28282880',
    fontSize: 14,
  },
  continueButtonText: {
    color: '#fff',
    fontSize: 18,
  },
  disabled: {
    opacity: 0.5,
  },
  alternate_mobile_field_wrapper: {
    padding: 10,
  },
  alternate_mobile_message_wrapper: {
    marginBottom: 10,
  },
  alternate_mobile_message: {
    color: '#f4433680',
    fontSize: 10,
  },
  alternate_mobile_button: {
    color: SecondaryColor,
    fontSize: 12,
    textDecorationLine: 'underline',
  },
  buttonNotchIssue: {
    marginBottom: 20,
  },
  ////form style
  couponFormWrapper: {
    backgroundColor: '#f1f3f6',
    padding: 1,
    borderRadius: 3,
    marginTop: 5,
    marginBottom: 5,
    marginRight: 8,
    marginLeft: 8,
    elevation: 5,
    shadowColor: '#bfbfbf',
    shadowOffset: {
      height: 0,
      width: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 2,
  },
  couponInputWrapper: {
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: '#fff',
    margin: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  couponInput: {
    backgroundColor: '#fff',
    marginRight: Platform.OS === 'ios' ? 10 : null,
    fontSize: 17,
    width: DeviceWidth - 150,
  },
  applyCouponButton: {
    width: Platform.OS === 'ios' ? 80 : 90,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#42A9E2',
    borderRadius: 3,
    height: 36,
  },
  applyCouponButtonText: {
    color: '#fff',
    fontSize: 14,
  },
  couponErrorText: {
    height: 'auto',
    color: colors.red,
    alignSelf: 'flex-start',
    fontSize: 14,
  },
  couponResponseWrapper: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 5,
  },
  couponResponseText: {
    fontSize: 13,
    color: SecondaryColor,
  },
  appliedCouponWrapper: {
    flexDirection: 'row',
    paddingBottom: 10,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  appliedCouponCodeWrapper: {
    backgroundColor: 'green',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 5,
    borderRadius: 50,
  },
  appliedCouponCode: {
    color: '#fff',
    marginRight: 3,
  },
  // couponRemoveWrapper: {
  // },
  couponRemoveText: {
    fontSize: 16,
    color: '#ff0000',
  },
  container: {
    flex: 1,
    marginBottom: 30,
  },
  item: {
    padding: 10,
    marginVertical: 5,
    marginHorizontal: 8,
    elevation: 2,
    backgroundColor: '#fff',
    shadowOpacity: 0.03,
    shadowRadius: 2,
  },
  title: {
    fontSize: 15,
    color: '#0f1f44',
  },
  titleDesc: {
    fontSize: 10,
  },
  couponeCodeTextView: {
    height: 20,
    width: 20,
    borderWidth: 1,
    borderRadius: 14,
    borderColor: colors.PattensBlue,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalMainView: {
    width: '100%',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  applyCouponcodeMainView: {
    height: 260,
    width: '93%',
    backgroundColor: colors.white,
    elevation: 2,
    shadowColor: '#bfbfbf',
    padding: 10,
    paddingBottom: 16,
    shadowOffset: {
      height: 0,
      width: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 2,
    borderRadius: 10,
  },
  textInputView: {
    width: '100%',
    minHeight: '10%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputWithError: {
    width: '100%',
    height: '30%',
    alignItems: 'center',
  },
  txtView: {width: '65%', height: '100%', justifyContent: 'center'},
  textInput: {
    fontSize: 14,
    height: '60%',
    borderBottomWidth: 0.3,
    borderBottomColor: '#C6D2DE',
  },
  editInput: {
    // fontSize: 14,
    // height: '60%',
    borderWidth: 0.5,
    borderColor: '#C6D2DE',
    paddingVertical: 4,
    width: '80%',
    paddingRight: 5,
    paddingLeft: 5,
    marginLeft: 5,
  },
  applyBtn: {
    width: '35%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  couponsTxt: {
    fontSize: 15,
    height: 20,
    fontWeight: '700',
  },
  codeBtn: {
    width: '100%',
    height: '70%',
    paddingTop: 20,
    paddingBottom: 10,
  },
  CouponModalView: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 30,
    borderBottomWidth: 0.3,
    borderBottomColor: '#C6D2DE',
  },
  orangeDot: {
    height: 14,
    width: 14,
    borderRadius: 14,
    backgroundColor: colors.orangeBtn,
  },
  couponCodeTxtView: {
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
});
