import {StyleSheet, Platform} from 'react-native';
import {
  DeviceWidth,
  DeviceHeight,
  SecondaryColor,
} from '../../config/environment';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import colors from '../../config/colors';

export const SearchPageStyle = StyleSheet.create({
  searchBoxWrapper: {
    flexDirection: 'row',
    backgroundColor: '#FFF',
    elevation: 2,
    shadowColor: '#bfbfbf',
    // justifyContent: 'space-between',

    shadowOffset: {
      height: 0,
      width: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 2,
  },
  backIconWrapper: {
    width: 50,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    height: Platform.OS === 'ios' ? 45 : 45,
  },
  inputField: {
    height: Platform.OS === 'ios' ? 45 : 45,
    width: DeviceWidth - 99,
    color: '#000',
    fontSize: 14,
  },
  emptySearchWrapper: {
    height: hp('70%'),
    width: wp('80%'),
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  noquerySearchWrapper: {
    height: DeviceHeight - 45,
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  searchResultWrapper: {
    backgroundColor: '#fff',
    marginBottom: '12%',
  },
  searchProduct: {
    paddingTop: 3,
    paddingBottom: 3,
    // flex: 1,
    borderBottomWidth: 0.5,
    borderBottomColor: '#ddd',
    marginLeft: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  productDetailWrapper: {
    width: DeviceWidth - 130,
    marginLeft: 5,
  },
  searchProductPriceWrapper: {
    flexDirection: 'row',
  },
  searchProductPrice: {
    marginRight: 5,
  },
  searchProductPriceStrike: {
    textDecorationLine: 'line-through',
    textDecorationStyle: 'solid',
  },
  searchImage: {
    width: 250,
    height: 250,
  },
  mainContainer: {
    width: wp('50%'),
    alignItems: 'center',
    backgroundColor: '#FFF',
  },
  cardBody: {
    flex: 1,
  },
  viewContainer: {
    width: wp('47%'),
    minHeight: wp('85.2%'),
    paddingHorizontal: wp('2%'),
    paddingVertical: hp('1%'),
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderRadius: hp('0.8%'),
    borderColor: '#D3D3D3',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  pricePercentageContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  mainPriceText: {
    lineHeight: 22,
    fontWeight: '500',
    fontSize: wp('3%'),
    marginRight: 5,
    color: '#25303C',
  },
  cutPrice: {
    lineHeight: 22,
    fontSize: wp('3%'),
    color: '#C4C4C4',
    textDecorationLine: 'line-through',
    textDecorationStyle: 'solid',
    marginRight: 5,
  },
  precentageText: {
    lineHeight: 22,
    fontSize: wp('3%'),
    color: '#25303C',
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    height: hp('3%'),
  },
  ratingText: {
    lineHeight: 24,
    fontWeight: '500',
    fontSize: wp('3.5%'),
    color: '#666666',
    marginRight: 10,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: hp('0.5%'),
  },
  addToCartButton: {
    borderWidth: 1,
    width: wp('32%'),
    paddingVertical: hp('1%'),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: hp('0.5%'),
    borderColor: colors.orangeBtn,
  },
  addToCartText: {
    fontWeight: 'bold',
    color: colors.orangeBtn,
  },
  wishlistButton: {
    borderWidth: 1,
    paddingVertical: hp('1%'),
    paddingHorizontal: wp('2%'),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: hp('0.5%'),
    borderColor: '#7C8697',
  },
  notFoundHeading: {
    fontWeight: 'bold',
    fontSize: wp('7%'),
    color: '#25303C',
  },
  notFoundSubHeading: {
    marginTop: hp('2%'),
    fontSize: wp('4.5%'),
    textAlign: 'center',
    lineHeight: 25,
    color: '#25303C',
  },
  notFoundText: {
    fontWeight: 'bold',
    color: 'red',
  },
  textFilterContainer: {
    paddingHorizontal: wp('2%'),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: hp('1%'),
  },
  filterButton: {
    borderRadius: hp('.5%'),
    backgroundColor: '#f3943d',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: hp('1%'),
    paddingHorizontal: wp('5%'),
    borderRadius: hp('.5%'),
    borderWidth: 1,
    borderColor: '#C4C4C4',
  },
  filterText: {
    marginLeft: wp('2%'),
    fontWeight: '500',
    color: 'gray',
  },
  filterContainer1: {
    paddingVertical: hp('0.5%'),
  },
  modalMainView: {
    flex: 1,
    width: '100%',
  },
  addressModalView: {
    justifyContent: 'flex-end',
  },

  modalHeaderView: {
    width: '100%',
    padding: 10,
    justifyContent: 'center',
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    marginTop: 30,
  },
  headerText: {
    fontSize: 16,
    fontWeight: '600',
    width: '100%',
    color: colors.white,
  },
  textStyle: {
    fontWeight: '400',
    textAlign: 'center',
    fontSize: 16,
    color: colors.black,
    paddingVertical: 5,
    alignSelf: 'center',
    width: '72%',
  },
  body: {
    // width: '100%',
    justifyContent: 'center',
    // paddingBottom: 10,
    paddingHorizontal: 10,
    // backgroundColor: 'red',
    // height: '100%',
    paddingBottom: hp('3%'),
    flex: 1,
  },
  textInput: {
    marginVertical: 5,
    padding: 5,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: colors.LightGray,
  },
  submitBtn: {
    // marginTop: hp('0.8%'),
    // borderRadius: hp('.5%'),
    // backgroundColor: '#fd9c44',
    // width: '100%',
    // height: hp('4.5%'),
    // justifyContent: 'center',
    // textAlign: 'center',
    width: '100%',
    height: hp('4.5%'),
    borderRadius: 30,
    backgroundColor: '#fd9c44',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  //sort Modal
  containerr: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  contentt: {
    height: '30%',
    // marginTop: hp('7%'),
    // flex: 1,
  },
  bodyy: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  filterContainerr: {
    backgroundColor: '#FFFFFF',
    width: wp('100%'),
  },
  headerr: {
    backgroundColor: '#fff',
    justifyContent: 'space-between',
    flexDirection: 'row',
    // height: hp('7%'),
  },
  footerr: {
    height: hp('8%'),
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 5,
  },
  filterHeadingg: {
    alignSelf: 'flex-start',
  },
  filterHeadingTextt: {
    color: 'black',
    marginTop: hp('0.8%'),
    padding: hp('1.5%'),
    marginLeft: hp('0.8%'),
    fontSize: hp('2.1%'),
    fontWeight: 'bold',
  },
  applyButtonn: {
    marginTop: hp('0.8%'),
    marginBottom: hp('1%'),
    borderRadius: hp('.5%'),
    backgroundColor: '#fd9c44',
    width: hp('20%'),
    height: hp('4.5%'),
    justifyContent: 'center',
    textAlign: 'center',
    marginLeft: hp('0.8%'),
  },
  cancleButtonn: {
    marginTop: hp('0.8%'),
    marginBottom: hp('1%'),
    borderRadius: hp('.5%'),
    backgroundColor: colors.LightGray,
    width: hp('20%'),
    height: hp('4.5%'),
    justifyContent: 'center',
    textAlign: 'center',
    marginRight: hp('0.8%'),
  },
  voice: {padding: 4, right: 8, justifyContent: 'center'},
  modelContinuer: {
    flex: 1,
    backgroundColor: 'rgba(37, 53, 65, 0.85)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  modelContinuerSub: {
    width: '100%',
    backgroundColor: '#FFF',
    borderRadius: 10,
    elevation: 8,
    alignItems: 'center',
  },
  imageContinuer: {alignSelf: 'flex-start', padding: 8},
  closeIcon: {
    width: 30,
    height: 30,
  },
  micView: {alignItems: 'center'},
  micImage: {width: 300, height: 180},
  voiceText: {
    fontSize: 20,
    paddingVertical: 10,
    paddingHorizontal: 16,
    textAlign: 'center',
    color: 'black',
    fontWeight: '500',
  },
  button: {
    width: '40%',
    backgroundColor: '#fc8340',
    padding: 10,
    borderRadius: 10,
    margin: 16,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFF',
    textAlign: 'center',
  },
});
